version: "3"
services:
  # microservice1:
  #   build:
  #     context: ./user-service
  #   ports:
  #     - "5000:5000"
  # microservice2:
  #   build:
  #     context: ./question-answer-service
  #   ports:
  #     - "5001:5000"
  microservice3:
    build:
      context: ./categories-service
    ports:
      - "5000:5002"
  mysqldb:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=p@ssw0rd1