version: "3"
services:
  microservice1:
    build:
      context: ./user-service
    ports:
      - "8000:5000"
  microservice2:
    build:
      context: ./question-answer-service
    ports:
      - "8001:5001"
  microservice3:
    build:
      context: ./categories-service
    ports:
      - "8002:5002"
  mysqldb:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=p@ssw0rd1